### ISSUE TITLE
phpunit didn't find tests by default

### ISSUE THREAD

**Issue by krylov123** [appwilio/russianpost-sdk#1]
Reproduce:

1. Clone repository
2. composer update
3. phpunit
4. Take output: "No tests executed!"

**Comment by greabock** [comment]
Run
```
 .\vendor\bin\phpunit
```

**Comment by krylov123** [comment]
That's will be working, for sure. Shame on my head ))
Will check it later - to be 100% sure. Then, maybe it need to be added to README?

**Comment by greabock** [comment]
I'll add it today
