### ISSUE TITLE
401 Unauthorized response

### ISSUE THREAD

**Issue by GingerN** [appwilio/russianpost-sdk#18]
Добрый день. Спасибо за вашу работу. Не знаю куда еще написать. Возможно, ошибка в моей невнимательности.

Появляется такая ошибка. Делаю все в точности как в разделе отправка в пунктах: Конфигурация, Расчёт стоимости пересылки (может, еще что-то необходимо настроить). Только использую свои логин, пароль и токен. Если вывести `dd($dispatching->services)`, ошибки еще нет. А при создании `$response = $dispatching->services->calculate(...)` появляется ошибка:
`ILLEGAL_CREDENTIALS - Ошибка авторизации пользователя: invalid_grant
Client error: POST https://otpravka-api.pochta.ru/1.0/tariff resulted in a 401 Unauthorized response`
У вас в конфигах логин и пароль называются по-разному: TRACKING и DISPATCHING для трекинга и отправки. Это имеет значение? Я брала из личного кабинета почты. Причем, из личного кабинета - это набор латинских букв, а на странице [генерации ключа](https://otpravka.pochta.ru/specification#/authorization-key) на сайте почты написано: Имя пользоватателя (емайл). Чей емайл... Токен я уже 10 раз проверила - скопирован из личного кабинета.

Пробовала добавлять в свои данные токена 'AccessToken ', появляется ошибка:
`cURL error 18: transfer closed with 103 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`, 
причем тоже на этапе `$response = $dispatching->services->calculate(...)`. Но вроде бы подпись 'AccessToken ' должна генерироваться со стороны вашего пакета, так что добавление этой подписи должно быть ненужно. Так?

Совершенно запуталась в каком месте происходит ошибка и какие данные являются неверными. Если поможете, буду очень благодарна.

**Comment by iamwildtuna** [comment]
Для API отправки токен высылается на email или берется из личного кабинета. Подробнее [тут](https://otpravka.pochta.ru/specification#/authorization-token). Остальные параметры - это логин и пароль от ЛК Почты России, по ним SDK [сам создает api key](https://github.com/appwilio/russianpost-sdk/blob/master/src/Dispatching/Http/Authentication.php#L30).

**Comment by GingerN** [comment]
Спасибо за ответ. Кстати, думаю, лучше в документации это указать. Это не совсем интуитивно понятно (что логин и пароль не от трекинга, а от лк), особенно когда возникает ошибка. Почему-то не получилось подключиться с вашим пакетом. С помощью пакета lapaygroup/russianpost при тех же данных все-таки получилось..

**Comment by jhaoda** [comment]
@GingerN спасибо! Документация доработана.
