### ISSUE TITLE
findOrderByTrackingNumber возвращает заказ с некорректными данными

### ISSUE THREAD

**Issue by mlavrinenko** [appwilio/russianpost-sdk#19]
`Appwilio\RussianPostSDK\Dispatching\Endpoints\Batches\Batches::findOrderByTrackingNumber` обращается к `/1.0/shipment/search`, который возвращает несколько объектов, а не один, за счет чего на выходе имеем Order внутри которого массив заказов.

Корректный вариант:
```php
    /**
     * @param  string  $barcode
     * @return Order[]|null
     */
    public function findOrdersByTrackingNumber(string $barcode)
    {
        return $this->client->get('/1.0/shipment/search', GenericRequest::create(['query' => $barcode]), new ArrayOf(Order::class));
    }
```

Слабо ориентируюсь в этом API, в моем случае $barcode это был внутренний номер заказа в интернет-магазине, а не трек-номер.

**Comment by jhaoda** [comment]
@mlavrinenko спасибо! Проверьте, пожалуйста на версии f901949.

**Comment by mlavrinenko** [comment]
@jhaoda Заработало, благодарю!
