### ISSUE TITLE
Как нам обсустроить API отправки

### ISSUE THREAD

**Issue by jhaoda** [appwilio/russianpost-sdk#5]
Предполагается что-то типа:

```php
$api->service->cleanPhone('89012345678');
$api->service->cleanAddress('Красноярск, Добрых Комбайнёров, 587');

$api->orders->create(new InputOrder(...));
$api->orders->find('56445645645');
```
и так далее.

Корневой класс:
```php
/**
 * @property-read Orders $orders
 * @property-read Service $services
 * @property-read Shipments $shipments
 * ...
 */
class Api
{
    // ...
}
```
cc @greabock @krylov123

**Comment by krylov123** [comment]
Вот какие мысли на данный момент.

```php
$api->orders->create(new InputOrder(...));
$response = $api->orders->find('56445645645');
```

В принципе, так себе и видел. Стиль довольно простой и понятный, в нем сразу прослеживается структура API. Однако, я набросал дальше и там возникают нюансы.

Например, при редактировании мы будем делать что-то такое:

```php
$response = $api->orders->find('56445645645');
$order = $response->body;

/** а дальше */
$order->courier = false;
$api->orders->edit($order);

/** в то время как интуитивно хочется чего-то вроде */
$order->courier = false;
$order->save();
```

Можно сделать на манер лары, это выглядело бы так:

```php
$order = new ApiOrder();
//либо
$order = ApiOrder::find('56445645645');

$order->courier = true;
$order->save();
```

Что проще "считывается" именно для пользователя пакета. Впрочем, можно последний вариант реализовать просто отдельным фасадом.
Но при неподходящей структуре классов фасад может получиться слишком "жирным".

**Comment by jhaoda** [comment]
```php
/** в то время как интуитивно хочется чего-то вроде */
$order->courier = false;
$order->save();
```
Это пахнет AR, чего хотелось бы избежать.

**Comment by krylov123** [comment]
Ну да, люблю все beginner friendly делать, вот прям хлебом не корми.

Но по существу согласен, давайте держаться SOLID. Если у @greabock нет дополнений, то я сюда скину примеры использования всех методов, чтобы проверить что других вопросов не возникает.

Затем можно переходить к файловой структуре и уже начать писать код ))
