### ISSUE TITLE
Что делаем с ошибками?

### ISSUE THREAD

**Issue by krylov123** [appwilio/russianpost-sdk#6]
## Что делаем с ошибками?

У нас есть следующие уровни ошибок
1. Все виды системных (ОС) ошибок
2. Ошибки при передаче запрос (http status code != 200 и тп)
3. Ошибки при парсинге ответа (API выдал null вместо json'а и тп)
4. Ошибки самого API в ответе ($errors[0]["error-code"] = "ALL_SHIPMENTS_SENT")

### Вопрос - когда выбрасывать Exception'ы, а когда просто строки error_code и error_message?

По аналогии с ларой можно реализовывать два метода:

```php
$orders->find('56445645645');
$orders->findOrFail('56445645645');
```

1. В первом случае Exception'ы выбрасываются на 1-3 уровни ошибок, а 4й уровень программист анализирует сам
```php
$response = $orders->find('56445645645');
if (is_null($response->body)) //мне важно только найден ли заказ
if (!empty($response->errors)) //мне важно почему не найден заказ
```

2. Во втором случае Exception'ы выбрасываются на всех уровнях ошибок
```php
try{
	$response = $orders->findOrFail('56445645645');
}catch(IncorrectOrderIdException $e){
	//Обработка такой ошибки с бизнес-логикой
}catch(APIException $e){
	//Уведомление пользователя об ошибке
}catch(Exception $e){
	//Все совсем плохо, только логгирование
}
```

`При этом IncorrectOrderIdException extends APIException `

К моменту когда это дописал - уже не уверен нужно ли реализовывать второй вариант, т.к. это очень много работы сверху. Много кастомных Exception'ов, которые к тому же надо маппить к кодам ошибки из документации.
Но уверен что такой вариант очень полезен в целом ряде задач.

Обсуждаем?

P.S: Судя по всему findOrFail довольно независим, т.е. в качестве компромисса можно сначала реализовать весь API только c find, а только потом думать над findOrFail.

**Comment by jhaoda** [comment]
Я обычно следую логике, что `find` может вернуть `null` или коллекцию сущностей, а `get` сущность или выкинуть исключение.
Тут мы можем схитрить и назвать метод как в API — `search` :wink: Что он вернёт, если не найдёт заказ?

**Comment by krylov123** [comment]
@jhaoda похоже в ПР сами не определились:

Например, при поиске заказа (номер заказа по базе отправителя):
`/1.0/backlog/search?query=11111111`
в ответ прилетает http status=200 и пустой body

В тоже время, при получении несуществующего заказа (id заказа по базе почты):
`/1.0/backlog/11111111`
в ответ прилетает http status=404

**Comment by krylov123** [comment]
@jhaoda по сути да, только нюанс в том что это методы получения заказа по разным id.
т.е. нас принуждают:

- если shop_id, то только find
- если pochta_id, то только get

И потом вспоминай в проекте, то ли empty($response) обрабатывать, то ли ждать GuzzleHttpException.

Было бы приятнее во всех случаях catch'ить свой NotFoundException и все.

```php
/** Но реализовать придется как-то так: */

//В первом методе
if (empty($response->body)) throw new NotFoundException();
return $response;

//Во втором методе
try{
    ...
}catch(GuzzleRequestException $e){
        if($e->getCode()==404) throw new NotFoundException();
        throw $e; //остальные выбрасываем как есть
}
```

**Comment by jhaoda** [comment]
@krylov123 не очень понятно, чем отличаются идентификаторы в этих методах.

**Comment by krylov123** [comment]
Первый идентификатор присваивает пользователь из своей системы, второй идентификатор генерирует почта.

**Comment by jhaoda** [comment]
@krylov123 т.е.
`/1.0/backlog/search?query=RA123456789RU`
`/1.0/backlog/11111111`

или наоборот?

**Comment by krylov123** [comment]
@jhaoda наоборот, причем, еще и не RA123456789RU а другой новый id, циферный. он вроде больше нигде не фигурирует, т.е. мы его просто при создании заказа узнаем.

**Comment by jhaoda** [comment]
@krylov123 другой это 14 цифр, он для РПО внутри страны.

**Comment by krylov123** [comment]
@jhaoda нет, он из 7 цифр состоит, т.е. итого у меня есть 3 id'шника сейчас

- номер заказа в магазине
- трекинг отслеживаения посылки
- внутренний id почты, который вроде бы нигде больше не используется
