### ISSUE TITLE
Ваш SDK еще живой?

### ISSUE THREAD

**Issue by mihdan** [appwilio/russianpost-sdk#9]
Все привет, реально ли ваш АПИ использовать в проекте, где надо общаться с АПИ почты России?

**Comment by jhaoda** [comment]
А почему он не должен быть живым? Мы используем.

**Comment by jhaoda** [comment]
@mihdan к сожалению, ПР уже два года не может дать нам доступ к разделу «Отправка», поэтому пока работает только трекинг. Несколько человек начинали работу над отправкой и калькулятором, но в итоге всё заглохло. С удовольствием примем помощь.

**Comment by mihdan** [comment]
Это в стиле ПР. Попробую помочь как разберусь с их чудо АПИ

**Comment by DiegoWtf** [comment]
Могу запулить реквестов для работы с отправкой. Сам пользуюсь этой либой https://github.com/BringerPro/russian-post-api-client-php

**Comment by jhaoda** [comment]
@DiegoWtf пульте. Но предварительно посмотрите #5, #6 и #7, чтобы понимать направление, в котором предполагается развитие SDK.

**Comment by DiegoWtf** [comment]
Хм, походу нужно подождать пока вы запулите первоначальный вид, а то на говнокодю тут...
Ещё у меня щас проблема с этой функцией https://otpravka.pochta.ru/specification#/documents-create_forms_backlog кто-нибудь ею пользовался? Мне выдает такую ошибку:
`{ "code" : "1001", "desc" : "Instance BacklogTuple not found for params: 326673", "sub-code" : "RESOURCE_NOT_FOUND" }`
В кач-ве параметра отправляю номер нашего заказа (по крайней мере у них в примере кода указан короткий номер не похожий на почтовый идентификатор). М.б. в личном кабинете они должны быть со статусом "Новый"?)

**Comment by jhaoda** [comment]
@DiegoWtf первый подход уже в ветке [dispatching](https://github.com/appwilio/russianpost-sdk/tree/dispatching).
